export const StackNav = {
  Splash: 'Splash',
  OnBoarding: 'OnBoarding',
  AuthNavigation: 'AuthNavigation',
  TabNavigation: 'TabNavigation',
  DiscoverByInterest: 'DiscoverByInterest',
  Chat: 'Chat',
  Profile: 'Profile',
  ChooseLanguage: 'ChooseLanguage',
  Setting: 'Setting',
  EditProfile: 'EditProfile',
  MatchesUserDetails: 'MatchesUserDetails',
  MatchDatingScreen: 'MatchDatingScreen',
  StoryView: 'StoryView',
};

export const AuthNav = {
  LogIn: 'LogIn',
  SignUp: 'SignUp',
  OtpVerify: 'OtpVerify',
  AccountName: 'AccountName',
  EnterBirthDate: 'EnterBirthDate',
  SelectGender: 'SelectGender',
  SelectInterest: 'SelectInterest',
  AboutScreen: 'AboutScreen',
  UploadPhoto: 'UploadPhoto',
  VerifyLoginOtp: 'VerifyLoginOtp',
  DogProfileName: 'DogProfileName',
  DogProfileAge: 'DogProfileAge',
  DogProfileGender: 'DogProfileGender',
  DogProfileBreed: 'DogProfileBreed',
  DogProfileNature: 'DogProfileNature',
  DogProfileBehavior: 'DogProfileBehavior',
  DogProfileSize: 'DogProfileSize',
  DogProfileTraining: 'DogProfileTraining',
  DogProfileAbout: 'DogProfileAbout',
};

export const TabNav = {
  HomeScreen: 'HomeScreen',
  ExploreScreen: 'ExploreScreen',
  AddPhoto: 'AddPhoto',
  MatchesScreen: 'MatchesScreen',
  MessageScreen: 'MessageScreen',
};
